# Generated by Django 4.2.2 on 2023-07-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='connect_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comments'),
        ),
    ]
