openapi: 3.0.2
info:
 title: 'Some application'
 version: '0.1'
paths:
 /schools/:
   get:
     operationId: listSchools
     description: 'List of posts'
     parameters: []
     responses:
       '200':
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: 'news'
         description: ''
     tags:
     - schools
   post:
     operationId: createSchool
     description: 'Create post'
     parameters: []
     requestBody:
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/School'
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/School'
         description: ''
     tags:
     - schools

 schemas:
   School:
     type: object
     properties:
       id:
         type: integer
         readOnly: true
       name:
         type: string
         maxLength: 64
     required:
     - name